name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.MOONTOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'  # Added caching for faster installations
          
      - name: Install Dependencies
        run: |
          npm ci
          npm install --save-dev @babel/plugin-proposal-private-property-in-object
          
      - name: Build
        env:
          CI: false
        run: npm run build
        
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          branch: gh-pages
          token: ${{ secrets.MOONTOKEN }}  # Updated to use MOONTOKEN
          clean: true